-- [SCVID]_Policies_07_Atomic
-- Author: Strudeler
-- DateCreated: 4/3/2021 12:08:03 PM
--------------------------------------------------------------
/*	ATOMIC POLICIES			*/
DELETE FROM Policies WHERE PolicyType = 'POLICY_CRYPTOGRAPHY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_INTERNATIONAL_WATERS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_CONTAINMENT';
DELETE FROM Policies WHERE PolicyType = 'POLICY_HERITAGE_TOURISM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_SPORTS_MEDIA';
DELETE FROM Policies WHERE PolicyType = 'POLICY_SATELLITE_BROADCASTS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_INTEGRATED_SPACE_CELL';
DELETE FROM Policies WHERE PolicyType = 'POLICY_STRATEGIC_AIR_FORCE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_SECOND_STRIKE_CAPABILITY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_AFTER_ACTION_REPORTS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MUSIC_CENSORSHIP';