-- [SCVID]_Policies_05_Industrial
-- Author: Strudeler
-- DateCreated: 4/3/2021 12:03:11 PM
--------------------------------------------------------------
/*	INDUSTRIAL POLICIES		*/
DELETE FROM Policies WHERE PolicyType = 'POLICY_NATIVE_CONQUEST';
DELETE FROM Policies WHERE PolicyType = 'POLICY_COLONIAL_TAXES';
DELETE FROM Policies WHERE PolicyType = 'POLICY_RAJ';
DELETE FROM Policies WHERE PolicyType = 'POLICY_PUBLIC_WORKS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_SKYSCRAPERS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_GRANDE_ARMEE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_NATIONAL_IDENTITY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_GRAND_OPERA';
DELETE FROM Policies WHERE PolicyType = 'POLICY_SYMPHONIES';
DELETE FROM Policies WHERE PolicyType = 'POLICY_PUBLIC_TRANSPORT';
DELETE FROM Policies WHERE PolicyType = 'POLICY_TOTAL_WAR';
DELETE FROM Policies WHERE PolicyType = 'POLICY_EXPROPRIATION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MILITARY_ORGANIZATION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MILITARY_RESEARCH';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MILITARY_FIRST';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FORCE_MODERNIZATION';