-- [SCVID]_ModSupport_01
-- Author: Strudeler
-- DateCreated: 4/9/2021 4:29:09 PM
--------------------------------------------------------------
/*	DELIVERATOR23'S STEEL AND THUNDER: UNIT EXPANSION						*/

/*	DELIVERATOR23'S STEEL AND THUNDER: UNIQUE UNITS							*/

/*	DELIVERATOR23'S STEEL AND THUNDER: EVERYTHING ELSE						*/

/*	GEDEMO'S FRANCE | NAPOLEON BONAPARTE (Broken)							*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_GEDEMO_NAPOLEON';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_GEDEMO_NAPOLEON'),			('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_GEDEMO_NAPOLEON');

/*	GEDEMO'S PHOENICIA | HANNIBAL BARCA										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_GEDEMO_HANNIBAL';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_GEDEMO_HANNIBAL'),			('RELIGION_STR_ETHNO_SEMITIC_BAALISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_GEDEMO_HANNIBAL');

/*	LEUGI'S INCA | FRANCISCO PIZARRO										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_LEU_PIZARRO_INCA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_LEU_PIZARRO_INCA'),		('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_LEU_PIZARRO_INCA');


/*	LEUGI'S SPAIN | FRANCISCO PIZARRO										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_LEU_PIZARRO_SPAIN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_LEU_PIZARRO_SPAIN'),		('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_LEU_PIZARRO_SPAIN');

/*	LEUGI'S MAPUCHE | ORELIE ANTOINE I										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_LEU_ORELIE';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_LEU_ORELIE'),				('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_LEU_PORFIRIO');

/*	LEUGI'S	MAYA | PACAL													*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_LEU_PACAL';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_LEU_PACAL'),				('RELIGION_STR_ETHNO_MAYAN_POPOL_VUH')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_LEU_PACAL');

/*	LEUGI'S MEXICO | PORFIRIO DIAZ	(Broken)								*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_LEU_PORFIRIO';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_LEU_PORFIRIO'),			('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_LEU_PORFIRIO');

/*	LEUGI'S BRAZIL | GETULIO VARGAS											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_LEU_VARGAS';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_LEU_VARGAS'),				('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_LEU_VARGAS');

/*	LEUGI'S MAYA | YAXKIN CAAN CHAC											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_LEU_YAXKIN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_LEU_YAXKIN'),				('RELIGION_STR_ETHNO_MAYAN_POPOL_VUH')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_LEU_YAXKIN');

/*	LEUGI'S/JFD'S AZTECS | CUAHTEMOC (Broken)								*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_CUAUHTEMOC';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_CUAUHTEMOC'),			('RELIGION_STR_ETHNO_NAHUA_TEOTLISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_CUAUHTEMOC');

/*	LEUGI'S AZTECS | ITZCOATL												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_LEU_ITZCOATL';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_LEU_ITZCOATL'),			('RELIGION_STR_ETHNO_NAHUA_TEOTLISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_LEU_ITZCOATL');

/*	MERRICK'S BULGARIA | SIMEON I											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_SIMEON_I';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_SIMEON_I'),			('RELIGION_STR_CHRIST_TRINITARIAN_ORTHODOX')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_SIMEON_I');

/*	MERRICK'S AUSTRIA | MARIA THERESA										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_MARIA_THERESA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_MARIA_THERESA'),		('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_MARIA_THERESA');

/*	MERRICK'S AUSTRIA | JOSEPH II											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_JOSEPH_II';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_JOSEPH_II'),			('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_JOSEPH_II');

/*	MERRICK'S ANGLO-SAXONS | ALFRED THE GREAT								*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_FB_ALFRED';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_FB_ALFRED'),				('RELIGION_STR_CHRIST_TRINITARIAN_ANGLICAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_FB_ALFRED');

/*	MERRICK'S ANGLO-SAXONS | OFA OF MERCIA									*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_FB_OFFA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_FB_OFFA'),					('RELIGION_STR_CHRIST_TRINITARIAN_ANGLICAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_FB_OFFA');

/*	MERRICK'S ANGLO-SAXONS | AETHELFLAED									*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_FB_AETHELFLAED';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_FB_AETHELFLAED'),			('RELIGION_STR_CHRIST_TRINITARIAN_ANGLICAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_FB_AETHELFLAED');

/*	MERRICK'S FINLAND | MANNERHEIM											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_MANNERHEIM';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_MANNERHEIM'),			('RELIGION_STR_CHRIST_TRINITARIAN_LUTHERAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_MANNERHEIM');

/*	MERRICK'S MALTA | JEAN DE VALETTE										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_JEAN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_JEAN'),				('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_JEAN');

/*	MERRICK'S PALMYRA | ODAENATHUS											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_ODAENATHUS';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_ODAENATHUS'),			('RELIGION_STR_ETHNO_SEMITIC_BAALISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_ODAENATHUS');

/*	MERRICK'S PALMYRA | ZENOBIA												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_ZENOBIA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_ZENOBIA'),				('RELIGION_STR_ETHNO_SEMITIC_BAALISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_ZENOBIA');

/*	MERRICK'S SICILY | ROGER II												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_ROGER_II';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_ROGER_II'),			('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_ROGER_II');

/*	MERRICK'S GREECE | POLYCRATES											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_POLYCRATES';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_POLYCRATES'),			('RELIGION_STR_ETHNO_LATINHELLENE_OLYMPIANISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_POLYCRATES');

/*	MERRICK'S GREECE | EPAMINONDAS											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_EPAMINONDAS';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_EPAMINONDAS'),				('RELIGION_STR_ETHNO_LATINHELLENE_OLYMPIANISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_EPAMINONDAS');

/*	MERRICK'S GREECE | PHEIDON												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_PHEIDON';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_PHEIDON'),				('RELIGION_STR_ETHNO_LATINHELLENE_OLYMPIANISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_PHEIDON');

/*	MERRICK'S VENICE | ENRICO DANDOLO										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_ENRICO';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_ENRICO'),				('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_ENRICO');

/*	MERRICK'S SWEDEN | CARL XII												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_FB_KARL_XII';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_FB_KARL_XII'),				('RELIGION_STR_CHRIST_TRINITARIAN_LUTHERAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_FB_KARL_XII');

/*	MERRICK'S SWEDEN | OSCAR II												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_OSCAR_II_SWEDEN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_OSCAR_II_SWEDEN'),		('RELIGION_STR_CHRIST_TRINITARIAN_LUTHERAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_OSCAR_II_SWEDEN');

/*	MERRICK'S NORWAY | OSCAR II												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_OSCAR_II_NORWAY';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_OSCAR_II_NORWAY'),		('RELIGION_STR_CHRIST_TRINITARIAN_LUTHERAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_OSCAR_II_NORWAY');

/*	MERRICK'S JAPAN | ENOMOTO TAKEAKI										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_ENOMOTO';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_ENOMOTO'),				('RELIGION_STR_ETHNO_JAPANESE_SHINTO')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_ENOMOTO');

/*	MERRICK'S KIEVAN RUS | YAROSLAV											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_YAROSLAV';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_YAROSLAV'),			('RELIGION_STR_CHRIST_TRINITARIAN_ORTHODOX')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_YAROSLAV');

/*	MERRICK'S FLANDERS | THIERRY											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_THIERRY';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_THIERRY'),				('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_THIERRY');

/*	MERRICK'S FLANDERS | JOAN												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_JOAN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_JOAN'),				('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_JOAN');

/*	MERRICK'S TLINGIT | GUSH XEEN											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_SHAKES';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_SHAKES'),				('RELIGION_STR_ETHNO_AMERINDIAN_RAVEN_TALES')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_SHAKES');

/*	MERRICK'S ASHANTI | KOFI TUTU											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_KOFI_TUTU';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_KOFI_TUTU'),			('RELIGION_STR_ETHNO_GHANA_AKOMISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_KOFI_TUTU');

/*	MERRICK'S SERBIA | KARADORDE											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_KARADORDE';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_KARADORDE'),			('RELIGION_STR_CHRIST_TRINITARIAN_ORTHODOX')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_KARADORDE');

/*	MERRICK'S HITTITES | SUPPILIUMA I										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_MER_SUPPILULIUMA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_MER_SUPPILULIUMA'),		('RELIGION_STR_ETHNO_ANATOLIAN_WURRUNKATTISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MER_SUPPILULIUMA');

/*	SUKRITACT'S SIAM | RAMKHAMHEANG											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_RAMKHAMHAENG';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_RAMKHAMHAENG'),		('RELIGION_STR_BUDDHIC_THERAVADA')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_RAMKHAMHAENG');

/*	SUKRITACT'S SIAM | CHULALONGKORN										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_CHULALONGKORN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_CHULALONGKORN'),		('RELIGION_STR_BUDDHIC_THERAVADA')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_CHULALONGKORN');

/*	SUKRITACT'S SIAM | NARAI												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_NARAI';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_NARAI'),			('RELIGION_STR_BUDDHIC_THERAVADA')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_NARAI');

/*	SUKRITACT'S ETHIOPIA | ZARA YAQOB										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_ZARAYAQOB';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_ZARAYAQOB'),			('RELIGION_STR_CHRIST_TRINITARIAN_MIAPHYSITE')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_ZARAYAQOB');

DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_ZARAYAQOB_DLC';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_ZARAYAQOB_DLC'),		('RELIGION_STR_CHRIST_TRINITARIAN_MIAPHYSITE')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_ZARAYAQOB_DLC');

/*	SUKRITACT'S ETHIOPIA | EZANA											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_EZANA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_EZANA'),				('RELIGION_STR_CHRIST_TRINITARIAN_MIAPHYSITE')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_EZANA');

DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_EZANA_DLC';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_EZANA_DLC'),			('RELIGION_STR_CHRIST_TRINITARIAN_MIAPHYSITE')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_EZANA_DLC');

/*	SUKRITACT'S EGYPT | SENUSRET III										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_SENUSRET_III';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_SENUSRET_III'),		('RELIGION_STR_ETHNO_EGYPTIAN_NETERISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_SENUSRET_III');

/*	SUKRITACT'S BURMA | BAYINNAUNG											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_BAYINNAUNG';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_BAYINNAUNG'),			('RELIGION_STR_BUDDHIC_THERAVADA')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_BAYINNAUNG');

/*	SUKRITACT'S SWAHILI | AL-HASAN IBN SULAIMAN								*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_AL_HASAN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_AL_HASAN'),			('RELIGION_STR_ISLAM_SUNNI')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_AL_HASAN');

/*	SUKRITACT'S PERSIA | KHOSROW I											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_KHOSROW_I';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_KHOSROW_I'),			('RELIGION_STR_MAZDAN_ZURVANISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_KHOSROW_I');

/*	SUKRITACT'S ICELAND | INGOLFUR ARNARSON									*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_INGOLFUR';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_INGOLFUR'),			('RELIGION_STR_ETHNO_GERMANIC_AESIRISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_INGOLFUR');

/*	SUKRITACT'S GAUL | VERCINGTORIX											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_VERCINGETORIX';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_VERCINGETORIX'),		('RELIGION_STR_ETHNO_CELTIC_DRUIDISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_VERCINGETORIX');
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_VERCINGETORIX_DLC';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_VERCINGETORIX_DLC'),	('RELIGION_STR_ETHNO_CELTIC_DRUIDISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_VERCINGETORIX_DLC');

/*	SUKRITACT'S ROME | HADRIAN												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_HADRIAN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_HADRIAN'),				('RELIGION_STR_ETHNO_LATINHELLENE_IMPERIAL_MYSTERIES')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_HADRIAN');

/*	SUKRITACT'S TIBET | TRISONG DETSEN										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_TRISONG_DETSEN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_TRISONG_DETSEN'),		('RELIGION_STR_BUDDHIC_VAJRAYANA')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_TRISONG_DETSEN');

/*	SUKRITACT'S TIBET | NGAWANG LOBSANG GYATSO								*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_LOBSANG_GYATSO';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_LOBSANG_GYATSO'),		('RELIGION_STR_BUDDHIC_VAJRAYANA')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_LOBSANG_GYATSO');

/*	SUKRITACT'S FRANCE | ROBESPIERRE										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_ROBESPIERRE';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_ROBESPIERRE'),			('RELIGION_STR_CHRIST_TRINITARIAN_EVANGELICAL')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_ROBESPIERRE');

/*	SUKRITACT'S AKAN | OSON													*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_SUK_OSON';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_SUK_OSON'),				('RELIGION_STR_ETHNO_GHANA_AKOMISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_SUK_OSON');

/*	JFD'S AMERICA | DONALD TRUMP											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_TRUMP';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_TRUMP'),				('RELIGION_STR_CHRIST_TRINITARIAN_EVANGELICAL')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_TRUMP');

/*	JFD'S GERMANY | ADOLF HITLER											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_HITLER';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_HITLER'),				('RELIGION_STR_ETHNO_GERMANIC_ASENISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_HITLER');

/*	JFD'S GERMANY | FREDERICK II											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_FREDERICK';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_FREDERICK'),			('RELIGION_STR_CHRIST_TRINITARIAN_LUTHERAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_FREDERICK');

/*	JFD'S SOVIET UNION | VLADIMIR LENIN										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_LENIN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_LENIN'),				('RELIGION_STR_CHRIST_TRINITARIAN_ORTHODOX')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_LENIN');

/*	JFD'S SOVIET UNION | JOSEPH STALIN										*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_STALIN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_STALIN'),				('RELIGION_STR_CHRIST_TRINITARIAN_ORTHODOX')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_STALIN');

/*	JFD'S WALES	| LLYWELYN													*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_LLYWELYN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_LLYWELYN'),			('RELIGION_STR_CHRIST_TRINITARIAN_INSULAR')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_LLYWELYN');

/*	JFD'S ITALY | MARGHERITA												*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_MARGHERITA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_MARGHERITA'),			('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_MARGHERITA');

/*	JFD'S ITALY | MUSSOLINI													*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_MUSSOLINI';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_MUSSOLINI'),			('RELIGION_STR_ETHNO_LATINHELLENE_IMPERIAL_MYSTERIES')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_MUSSOLINI');

/*	JFD'S RUSSIA | PUTIN													*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_PUTIN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_PUTIN'),				('RELIGION_STR_CHRIST_TRINITARIAN_ORTHODOX')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_PUTIN');

/*	JFD'S PAPAL STATES | PIUS IX											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_PUTIN';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_PUTIN'),				('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_PUTIN');

/*	JFD'S PAPAL STATES | GREGORY I											*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_JFD_GREGORY';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_JFD_GREGORY'),				('RELIGION_STR_CHRIST_TRINITARIAN_CATHOLIC')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_JFD_GREGORY');

/*	DELIVERATOR/GEDEMO/STEFFALON | WILLIAM									*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_WILLIAM_OF_ORANGE';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_WILLIAM_OF_ORANGE'),		('RELIGION_STR_CHRIST_TRINITARIAN_CALVINIST')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_WILLIAM_OF_ORANGE');

/*	DELIVERATOR/GEDEMO/STEFFALON | OTTO VON BISMARCK						*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_GEDEMO_BISMARK';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_GEDEMO_BISMARK'),			('RELIGION_STR_CHRIST_TRINITARIAN_LUTHERAN')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_GEDEMO_BISMARK');

/*	DELIVERATOR/SAILOR CAT/SEELING CAT/DIGIHUMAN'S INDONESIA | GAJAH MADA	*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_CVS_GAJAH_MADA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_CVS_GAJAH_MADA'),			('RELIGION_STR_BUDDHIC_THERAVADA')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_CVS_GAJAH_MADA');

/*	DELIVERATOR/SAILOR CAT/SEELING CAT/DIGIHUMAN/SALT'S PERSIA | DARIUS		*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_CVS_DARIUS';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_CVS_DARIUS'),				('RELIGION_STR_MAZDAN_ZOROASTRIANISM')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_CVS_DARIUS');

/*	DELIVERATOR/SAILOR CAT/SEELING CAT/DIGIHUMAN/SALT'S SONGHAI | ASKIYA	*/
DELETE FROM FavoredReligions WHERE LeaderType = 'LEADER_CVS_ASKIYA';

INSERT OR REPLACE INTO	FavoredReligions
						(LeaderType,						ReligionType)
				SELECT	('LEADER_CVS_ASKIYA'),				('RELIGION_STR_ISLAM_SUNNI')
WHERE EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_CVS_ASKIYA');
