-- [SCVID]_Policies_09_Future
-- Author: Strudeler
-- DateCreated: 4/3/2021 12:12:14 PM
--------------------------------------------------------------
/*	FUTURE POLICIES			*/
DELETE FROM Policies WHERE PolicyType = 'POLICY_FUTURE_VICTORY_SCIENCE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FUTURE_COUNTER_CULTURE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FUTURE_VICTORY_CULTURE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FUTURE_COUNTER_SCIENCE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FUTURE_VICTORY_DOMINATION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FUTURE_COUNTER_DIPLOMATIC';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FUTURE_VICTORY_DIPLOMATIC';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FUTURE_COUNTER_DOMINATION';
