-- [SCVID]_Policies_03_Medieval
-- Author: Strudeler
-- DateCreated: 4/3/2021 12:00:59 PM
--------------------------------------------------------------
/*	MEDIEVAL POLICIES		*/
DELETE FROM Policies WHERE PolicyType = 'POLICY_NAVAL_INFRASTRUCTURE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_NAVIGATION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FEUDAL_CONTRACT';
DELETE FROM Policies WHERE PolicyType = 'POLICY_SERFDOM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_RETAINERS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MERITOCRACY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_SACK';
DELETE FROM Policies WHERE PolicyType = 'POLICY_PROFESSIONAL_ARMY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_TRADE_CONFEDERATION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MERCHANT_CONFEDERATION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_AESTHETICS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MEDINA_QUARTER';
DELETE FROM Policies WHERE PolicyType = 'POLICY_CRAFTSMEN';
DELETE FROM Policies WHERE PolicyType = 'POLICY_TOWN_CHARTERS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_TRAVELING_MERCHANTS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_CHIVALRY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_GOTHIC_ARCHITECTURE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_CIVIL_PRESTIGE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_RETINUES';