-- [SCVID]_Units_New_01
-- Author: Strudeler
-- DateCreated: 4/23/2021 2:19:12 AM
--------------------------------------------------------------

/*	UNIT TAGS								*/
INSERT INTO Tags
			(Tag,							Vocabulary)
	VALUES	('CLASS_STR_THE_SAOSHYANT',		'ABILITY_CLASS'),
			('CLASS_STR_COMBAT_ENGINEER',	'ABILITY_CLASS'),
			('CLASS_STR_MILITARY_POLICE',	'ABILITY_CLASS'),
			('CLASS_STR_NAVAL_SURFACE',		'ABILITY_CLASS'),
			('CLASS_STR_NAVAL_CORVETTE',	'ABILITY_CLASS'),
			('CLASS_STR_NAVAL_CAPITAL',		'ABILITY_CLASS'),
			('CLASS_STR_AXEMAN',			'ABILITY_CLASS'),
			('CLASS_STR_ARMED_PILGRIM',		'ABILITY_CLASS'),
			('CLASS_STR_JUND_RIDER',		'ABILITY_CLASS'),
			('CLASS_STR_WOLF_WARRIOR',		'ABILITY_CLASS'),
			('CLASS_STR_EQUESTRIAN',		'ABILITY_CLASS'),
			('CLASS_STR_JAGUAR_WARRIOR',	'ABILITY_CLASS'),
			('CLASS_STR_CATAPHRACT',		'ABILITY_CLASS'),
			('CLASS_STR_HEADHUNTER',		'ABILITY_CLASS'),
			('CLASS_STR_PHAROAHS_GUARD',	'ABILITY_CLASS'),
			('CLASS_STR_ZEALOT',			'ABILITY_CLASS'),
			('CLASS_STR_WHITE_ELEPHANT',	'ABILITY_CLASS');