-- [SCVID]_Policies_10_Dark
-- Author: Strudeler
-- DateCreated: 4/3/2021 12:14:22 PM
--------------------------------------------------------------
/*	DARK AGE POLICIES		*/
DELETE FROM Policies WHERE PolicyType = 'POLICY_MONASTICISM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_TWILIGHT_VALOR';
DELETE FROM Policies WHERE PolicyType = 'POLICY_INQUISITION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_ISOLATIONISM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_LETTERS_OF_MARQUE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_ROBBER_BARONS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_ELITE_FORCES';
DELETE FROM Policies WHERE PolicyType = 'POLICY_COLLECTIVISM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_ROGUE_STATE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FLOWER_POWER';
DELETE FROM Policies WHERE PolicyType = 'POLICY_CYBER_WARFARE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_AUTOMATED_WORKFORCE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_DISINFORMATION_CAMPAIGN';