-- [SCVID]_Policies_04_Renaissance
-- Author: Strudeler
-- DateCreated: 4/3/2021 12:03:45 PM
--------------------------------------------------------------
/*	RENAISSANCE POLICIES	*/
DELETE FROM Policies WHERE PolicyType = 'POLICY_PRESS_GANGS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_COLONIAL_OFFICES';
DELETE FROM Policies WHERE PolicyType = 'POLICY_INVENTION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FRESCOES';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MACHIAVELLIANISM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_WARS_OF_RELIGION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_RELIGIOUS_ORDERS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_SIMULTANEUM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_LOGISTICS';
DELETE FROM Policies WHERE PolicyType = 'POLICY_TRIANGULAR_TRADE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_RATIONALISM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FREE_MARKET';
DELETE FROM Policies WHERE PolicyType = 'POLICY_LIBERALISM';
DELETE FROM Policies WHERE PolicyType = 'POLICY_WISSELBANKEN';
DELETE FROM Policies WHERE PolicyType = 'POLICY_DRILL_MANUALS';