-- [SCVID]_Policies_06_Modern
-- Author: Strudeler
-- DateCreated: 4/3/2021 12:06:12 PM
--------------------------------------------------------------
/*	MODERN POLICIES			*/
DELETE FROM Policies WHERE PolicyType = 'POLICY_RESOURCE_MANAGEMENT';
DELETE FROM Policies WHERE PolicyType = 'POLICY_PROPAGANDA';
DELETE FROM Policies WHERE PolicyType = 'POLICY_LEVEE_EN_MASSE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_LAISSEZ_FAIRE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MARKET_ECONOMY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_NOBEL_PRIZE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_NUCLEAR_ESPIONAGE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_POLICE_STATE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_ECONOMIC_UNION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FINEST_HOUR';
DELETE FROM Policies WHERE PolicyType = 'POLICY_ARSENAL_OF_DEMOCRACY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_NEW_DEAL';
DELETE FROM Policies WHERE PolicyType = 'POLICY_LIGHTNING_WARFARE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_THIRD_ALTERNATIVE';
DELETE FROM Policies WHERE PolicyType = 'POLICY_MARTIAL_LAW';
DELETE FROM Policies WHERE PolicyType = 'POLICY_GUNBOAT_DIPLOMACY';
DELETE FROM Policies WHERE PolicyType = 'POLICY_FIVE_YEAR_PLAN';
DELETE FROM Policies WHERE PolicyType = 'POLICY_COLLECTIVIZATION';
DELETE FROM Policies WHERE PolicyType = 'POLICY_PATRIOTIC_WAR';
DELETE FROM Policies WHERE PolicyType = 'POLICY_DEFENSE_OF_MOTHERLAND';